dataset: mnist
seed: 0
model: greedy
N: 1024
layers: 4
similarity: cosine   # or "l2"
tau: 0.1
lambda_ace: 0.1
batch_size: 128
epochs: 60
lr: 0.001
weight_decay: 0.0001
scheduler: cosine
warmup_ratio: 0.05
num_workers: 4
