dataset: cifar100
seed: 0
model: greedy
N: 4096
layers: 4
similarity: cosine   # or "l2"
tau: 0.1
lambda_ace: 0.1
batch_size: 128
epochs: 300
lr: 0.001
weight_decay: 0.0001
scheduler: cosine
warmup_ratio: 0.05
num_workers: 4
metrics_log_frequency: 5  # Log metrics every N iterations
